test_that("use", {
  expect_silent(check_stac(0))
  expect_silent(check_stac(1))
  expect_error(check_stac(-1))
  expect_error(check_stac(7))
  expect_error(check_stac(c(1, 2)))
  expect_error(check_stac(-1))
  expect_error(check_stac(NULL))
  expect_error(check_stac(NA))
  expect_error(check_stac(Inf))
  expect_error(check_stac(c()))
  expect_error(check_stac(list()))
  expect_error(check_stac("nonsense"))
})
