test_that("use", {
  expect_silent(check_species_type("A"))
  expect_silent(check_species_type("C"))
  expect_silent(check_species_type("I"))
  expect_error(check_species_type("X"))
  expect_error(check_species_type(c("A", "C")))
  expect_error(check_species_type(-1))
  expect_error(check_species_type(NULL))
  expect_error(check_species_type(NA))
  expect_error(check_species_type(Inf))
  expect_error(check_species_type(c()))
  expect_error(check_species_type(list()))
  expect_error(check_species_type("nonsense"))
})
