# ggplot2::theme(title = ggplot2::element_text(size = 10),
#                text = ggplot2::element_text(size = 7),
#                axis.text.y = ggtext::element_markdown(),
#                axis.text.x = ggtext::element_markdown()) +
#   ggplot2::scale_x_continuous(
#     breaks = create_plot_breaks(lower_lim = lower_clado,
#                                 upper_lim = upper_clado,
#                                 accuracy = 0.1,
#                                 round_func = floor),
#     labels = create_plot_labels(lower_lim = lower_clado,
#                                 upper_lim = upper_clado,
#                                 accuracy = 0.1,
#                                 round_func = floor),
#     limits = c(lower_clado, upper_clado),
#     trans = scales::trans_new(name = "ihs",
#                               transform = asinh,
#                               inverse = sinh))
#
# ggplot2::theme(title = ggplot2::element_text(size = 10),
#                text = ggplot2::element_text(size = 7),
#                axis.text.y = ggtext::element_markdown(),
#                axis.text.x = ggtext::element_markdown()) +
#   ggplot2::scale_x_continuous(
#     breaks = create_plot_breaks(lower_lim = lower_ext,
#                                 upper_lim = upper_ext,
#                                 accuracy = 0.1,
#                                 round_func = floor),
#     labels = create_plot_labels(lower_lim = lower_ext,
#                                 upper_lim = upper_ext,
#                                 accuracy = 0.1,
#                                 round_func = floor),
#     limits = c(lower_ext, upper_ext),
#     trans = scales::trans_new(name = "ihs",
#                               transform = asinh,
#                               inverse = sinh))
#
# ggplot2::theme(title = ggplot2::element_text(size = 10),
#                text = ggplot2::element_text(size = 7),
#                axis.text.y = ggtext::element_markdown(),
#                axis.text.x = ggtext::element_markdown()) +
#   ggplot2::scale_x_continuous(
#     breaks = create_plot_breaks(lower_lim = lower_immig,
#                                 upper_lim = upper_immig,
#                                 accuracy = 0.001,
#                                 round_func = floor),
#     labels = create_plot_labels(lower_lim = lower_immig,
#                                 upper_lim = upper_immig,
#                                 accuracy = 0.001,
#                                 round_func = floor),
#     limits = c(lower_immig, upper_immig),
#     trans = scales::trans_new(name = "ihs",
#                               transform = asinh,
#                               inverse = sinh))
#
# ggplot2::theme(title = ggplot2::element_text(size = 10),
#                text = ggplot2::element_text(size = 7),
#                axis.text.y = ggtext::element_markdown(),
#                axis.text.x = ggtext::element_markdown()) +
#   ggplot2::scale_x_continuous(
#     breaks = create_plot_breaks(lower_lim = lower_ana,
#                                 upper_lim = upper_ana,
#                                 accuracy = 0.1,
#                                 round_func = floor),
#     labels = create_plot_labels(lower_lim = lower_ana,
#                                 upper_lim = upper_ana,
#                                 accuracy = 0.1,
#                                 round_func = floor),
#     limits = c(lower_ana, upper_ana),
#     trans = scales::trans_new(name = "ihs",
#                               transform = asinh,
#                               inverse = sinh))
#
# ggplot2::theme(legend.position = "none",
#                title = ggplot2::element_text(size = 10),
#                text = ggplot2::element_text(size = 7),
#                axis.text.y = ggtext::element_markdown(),
#                axis.text.x = ggtext::element_markdown()) +
#   ggplot2::scale_y_continuous(
#     breaks = create_plot_breaks(lower_lim = lower_ext,
#                                 upper_lim = upper_ext,
#                                 accuracy = 0.1,
#                                 round_func = floor),
#     labels = create_plot_labels(lower_lim = lower_ext,
#                                 upper_lim = upper_ext,
#                                 accuracy = 0.1,
#                                 round_func = floor),
#     limits = c(lower_ext, upper_ext),
#     trans = scales::trans_new(name = "ihs",
#                               transform = asinh,
#                               inverse = sinh)) +
#   ggplot2::scale_x_continuous(
#     breaks = create_plot_breaks(lower_lim = lower_clado,
#                                 upper_lim = upper_clado,
#                                 accuracy = 0.1,
#                                 round_func = floor),
#     labels = create_plot_labels(lower_lim = lower_clado,
#                                 upper_lim = upper_clado,
#                                 accuracy = 0.1,
#                                 round_func = floor),
#     limits = c(lower_clado, upper_clado),
#     trans = scales::trans_new(name = "ihs",
#                               transform = asinh,
#                               inverse = sinh))
#
# ggplot2::theme(legend.position = "none",
#                title = ggplot2::element_text(size = 10),
#                text = ggplot2::element_text(size = 7),
#                axis.text.y = ggtext::element_markdown(),
#                axis.text.x = ggtext::element_markdown()) +
#   ggplot2::scale_y_continuous(
#     breaks = create_plot_breaks(lower_lim = lower_immig,
#                                 upper_lim = upper_immig,
#                                 accuracy = 0.001,
#                                 round_func = floor),
#     labels = create_plot_labels(lower_lim = lower_immig,
#                                 upper_lim = upper_immig,
#                                 accuracy = 0.001,
#                                 round_func = floor),
#     limits = c(lower_immig, upper_immig),
#     trans = scales::trans_new(name = "ihs",
#                               transform = asinh,
#                               inverse = sinh)) +
#   ggplot2::scale_x_continuous(
#     breaks = create_plot_breaks(lower_lim = lower_clado,
#                                 upper_lim = upper_clado,
#                                 accuracy = 0.1,
#                                 round_func = floor),
#     labels = create_plot_labels(lower_lim = lower_clado,
#                                 upper_lim = upper_clado,
#                                 accuracy = 0.1,
#                                 round_func = floor),
#     limits = c(lower_clado, upper_clado),
#     trans = scales::trans_new(name = "ihs",
#                               transform = asinh,
#                               inverse = sinh))
#
# ggplot2::theme(legend.position = "none",
#                title = ggplot2::element_text(size = 10),
#                text = ggplot2::element_text(size = 7),
#                axis.text.y = ggtext::element_markdown(),
#                axis.text.x = ggtext::element_markdown()) +
#   ggplot2::scale_y_continuous(
#     breaks = create_plot_breaks(lower_lim = lower_ana,
#                                 upper_lim = upper_ana,
#                                 accuracy = 0.1,
#                                 round_func = floor),
#     labels = create_plot_labels(lower_lim = lower_ana,
#                                 upper_lim = upper_ana,
#                                 accuracy = 0.1,
#                                 round_func = floor),
#     limits = c(lower_ana, upper_ana),
#     trans = scales::trans_new(name = "ihs",
#                               transform = asinh,
#                               inverse = sinh)) +
#   ggplot2::scale_x_continuous(
#     breaks = create_plot_breaks(lower_lim = lower_clado,
#                                 upper_lim = upper_clado,
#                                 accuracy = 0.1,
#                                 round_func = floor),
#     labels = create_plot_labels(lower_lim = lower_clado,
#                                 upper_lim = upper_clado,
#                                 accuracy = 0.1,
#                                 round_func = floor),
#     limits = c(lower_clado, upper_clado),
#     trans = scales::trans_new(name = "ihs",
#                               transform = asinh,
#                               inverse = sinh))
# ggplot2::theme(legend.position = "none",
#                title = ggplot2::element_text(size = 10),
#                text = ggplot2::element_text(size = 7),
#                axis.text.y = ggtext::element_markdown(),
#                axis.text.x = ggtext::element_markdown()) +
#   ggplot2::scale_y_continuous(
#     breaks = create_plot_breaks(lower_lim = lower_immig,
#                                 upper_lim = upper_immig,
#                                 accuracy = 0.001,
#                                 round_func = floor),
#     labels = create_plot_labels(lower_lim = lower_immig,
#                                 upper_lim = upper_immig,
#                                 accuracy = 0.001,
#                                 round_func = floor),
#     limits = c(lower_immig, upper_immig),
#     trans = scales::trans_new(name = "ihs",
#                               transform = asinh,
#                               inverse = sinh)) +
#   ggplot2::scale_x_continuous(
#     breaks = create_plot_breaks(lower_lim = lower_ext,
#                                 upper_lim = upper_ext,
#                                 accuracy = 0.1,
#                                 round_func = floor),
#     labels = create_plot_labels(lower_lim = lower_ext,
#                                 upper_lim = upper_ext,
#                                 accuracy = 0.1,
#                                 round_func = floor),
#     limits = c(lower_ext, upper_ext),
#     trans = scales::trans_new(name = "ihs",
#                               transform = asinh,
#                               inverse = sinh))
#
# ggplot2::theme(legend.position = "none",
#                title = ggplot2::element_text(size = 10),
#                text = ggplot2::element_text(size = 7),
#                axis.text.y = ggtext::element_markdown(),
#                axis.text.x = ggtext::element_markdown()) +
#   ggplot2::scale_y_continuous(
#     breaks = create_plot_breaks(lower_lim = lower_ana,
#                                 upper_lim = upper_ana,
#                                 accuracy = 0.1,
#                                 round_func = floor),
#     labels = create_plot_labels(lower_lim = lower_ana,
#                                 upper_lim = upper_ana,
#                                 accuracy = 0.1,
#                                 round_func = floor),
#     limits = c(lower_ana, upper_ana),
#     trans = scales::trans_new(name = "ihs",
#                               transform = asinh,
#                               inverse = sinh)) +
#   ggplot2::scale_x_continuous(
#     breaks = create_plot_breaks(lower_lim = lower_ext,
#                                 upper_lim = upper_ext,
#                                 accuracy = 0.1,
#                                 round_func = floor),
#     labels = create_plot_labels(lower_lim = lower_ext,
#                                 upper_lim = upper_ext,
#                                 accuracy = 0.1,
#                                 round_func = floor),
#     limits = c(lower_ext, upper_ext),
#     trans = scales::trans_new(name = "ihs",
#                               transform = asinh,
#                               inverse = sinh))
#
# ggplot2::theme(legend.position = "none",
#                title = ggplot2::element_text(size = 10),
#                text = ggplot2::element_text(size = 7),
#                axis.text.y = ggtext::element_markdown(),
#                axis.text.x = ggtext::element_markdown()) +
#   ggplot2::scale_y_continuous(
#     breaks = create_plot_breaks(lower_lim = lower_ana,
#                                 upper_lim = upper_ana,
#                                 accuracy = 0.1,
#                                 round_func = floor),
#     labels = create_plot_labels(lower_lim = lower_ana,
#                                 upper_lim = upper_ana,
#                                 accuracy = 0.1,
#                                 round_func = floor),
#     limits = c(lower_ana, upper_ana),
#     trans = scales::trans_new(name = "ihs",
#                               transform = asinh,
#                               inverse = sinh)) +
#   ggplot2::scale_x_continuous(
#     breaks = create_plot_breaks(lower_lim = lower_immig,
#                                 upper_lim = upper_immig,
#                                 accuracy = 0.001,
#                                 round_func = floor),
#     labels = create_plot_labels(lower_lim = lower_immig,
#                                 upper_lim = upper_immig,
#                                 accuracy = 0.001,
#                                 round_func = floor),
#     limits = c(lower_immig, upper_immig),
#     trans = scales::trans_new(name = "ihs",
#                               transform = asinh,
#                               inverse = sinh))
#
# ggplot2::theme(title = ggplot2::element_text(size = 10),
#                text = ggplot2::element_text(size = 7),
#                axis.text.y = ggtext::element_markdown(),
#                axis.text.x = ggtext::element_markdown()) +
#   ggplot2::scale_y_continuous(
#     breaks = create_plot_breaks(lower_lim = lower_clado_ratios,
#                                 upper_lim = upper_clado_ratios,
#                                 accuracy = 0.01,
#                                 round_func = floor),
#     labels = create_plot_labels(lower_lim = lower_clado_ratios,
#                                 upper_lim = upper_clado_ratios,
#                                 accuracy = 0.01,
#                                 round_func = floor),
#     limits = c(lower_clado_ratios, upper_clado_ratios),
#     trans = scales::trans_new(name = "ihs",
#                               transform = asinh,
#                               inverse = sinh)) +
#   ggplot2::scale_x_continuous(
#     breaks = create_plot_breaks(lower_lim = lower_ext_ratios,
#                                 upper_lim = upper_ext_ratios,
#                                 accuracy = 0.01,
#                                 round_func = floor),
#     labels = create_plot_labels(lower_lim = lower_ext_ratios,
#                                 upper_lim = upper_ext_ratios,
#                                 accuracy = 0.01,
#                                 round_func = floor),
#     limits = c(lower_ext_ratios, upper_ext_ratios),
#     trans = scales::trans_new(name = "ihs",
#                               transform = asinh,
#                               inverse = sinh))
#
# ggplot2::theme(title = ggplot2::element_text(size = 10),
#                text = ggplot2::element_text(size = 7),
#                axis.text.y = ggtext::element_markdown(),
#                axis.text.x = ggtext::element_markdown()) +
#   ggplot2::scale_y_continuous(
#     breaks = create_plot_breaks(lower_lim = lower_clado_ratios,
#                                 upper_lim = upper_clado_ratios,
#                                 accuracy = 0.01,
#                                 round_func = floor),
#     labels = create_plot_labels(lower_lim = lower_clado_ratios,
#                                 upper_lim = upper_clado_ratios,
#                                 accuracy = 0.01,
#                                 round_func = floor),
#     limits = c(lower_clado_ratios, upper_clado_ratios),
#     trans = scales::trans_new(name = "ihs",
#                               transform = asinh,
#                               inverse = sinh)) +
#   ggplot2::scale_x_continuous(
#     breaks = create_plot_breaks(lower_lim = lower_immig_ratios,
#                                 upper_lim = upper_immig_ratios,
#                                 accuracy = 0.001,
#                                 round_func = floor),
#     labels = create_plot_labels(lower_lim = lower_immig_ratios,
#                                 upper_lim = upper_immig_ratios,
#                                 accuracy = 0.001,
#                                 round_func = floor),
#     limits = c(lower_immig_ratios, upper_immig_ratios),
#     trans = scales::trans_new(name = "ihs",
#                               transform = asinh,
#                               inverse = sinh))
#
# ggplot2::theme(title = ggplot2::element_text(size = 10),
#                text = ggplot2::element_text(size = 7),
#                axis.text.y = ggtext::element_markdown(),
#                axis.text.x = ggtext::element_markdown()) +
#   ggplot2::scale_y_continuous(
#     breaks = create_plot_breaks(lower_lim = lower_clado_ratios,
#                                 upper_lim = upper_clado_ratios,
#                                 accuracy = 0.01,
#                                 round_func = floor),
#     labels = create_plot_labels(lower_lim = lower_clado_ratios,
#                                 upper_lim = upper_clado_ratios,
#                                 accuracy = 0.01,
#                                 round_func = floor),
#     limits = c(lower_clado_ratios, upper_clado_ratios),
#     trans = scales::trans_new(name = "ihs",
#                               transform = asinh,
#                               inverse = sinh)) +
#   ggplot2::scale_x_continuous(
#     breaks = create_plot_breaks(lower_lim = lower_ana_ratios,
#                                 upper_lim = upper_ana_ratios,
#                                 accuracy = 0.01,
#                                 round_func = floor),
#     labels = create_plot_labels(lower_lim = lower_ana_ratios,
#                                 upper_lim = upper_ana_ratios,
#                                 accuracy = 0.01,
#                                 round_func = floor),
#     limits = c(lower_ana_ratios, upper_ana_ratios),
#     trans = scales::trans_new(name = "ihs",
#                               transform = asinh,
#                               inverse = sinh))
#
# ggplot2::theme(title = ggplot2::element_text(size = 10),
#                text = ggplot2::element_text(size = 7),
#                axis.text.y = ggtext::element_markdown(),
#                axis.text.x = ggtext::element_markdown()) +
#   ggplot2::scale_y_continuous(
#     breaks = create_plot_breaks(lower_lim = lower_ext_ratios,
#                                 upper_lim = upper_ext_ratios,
#                                 accuracy = 0.01,
#                                 round_func = floor),
#     labels = create_plot_labels(lower_lim = lower_ext_ratios,
#                                 upper_lim = upper_ext_ratios,
#                                 accuracy = 0.01,
#                                 round_func = floor),
#     limits = c(lower_ext_ratios, upper_ext_ratios),
#     trans = scales::trans_new(name = "ihs",
#                               transform = asinh,
#                               inverse = sinh)) +
#   ggplot2::scale_x_continuous(
#     breaks = create_plot_breaks(lower_lim = lower_immig_ratios,
#                                 upper_lim = upper_immig_ratios,
#                                 accuracy = 0.001,
#                                 round_func = floor),
#     labels = create_plot_labels(lower_lim = lower_immig_ratios,
#                                 upper_lim = upper_immig_ratios,
#                                 accuracy = 0.001,
#                                 round_func = floor),
#     limits = c(lower_immig_ratios, upper_immig_ratios),
#     trans = scales::trans_new(name = "ihs",
#                               transform = asinh,
#                               inverse = sinh))
#
# ggplot2::theme(title = ggplot2::element_text(size = 10),
#                text = ggplot2::element_text(size = 7),
#                axis.text.y = ggtext::element_markdown(),
#                axis.text.x = ggtext::element_markdown()) +
#   ggplot2::scale_y_continuous(
#     breaks = create_plot_breaks(lower_lim = lower_ext_ratios,
#                                 upper_lim = upper_ext_ratios,
#                                 accuracy = 0.01,
#                                 round_func = floor),
#     labels = create_plot_labels(lower_lim = lower_ext_ratios,
#                                 upper_lim = upper_ext_ratios,
#                                 accuracy = 0.01,
#                                 round_func = floor),
#     limits = c(lower_ext_ratios, upper_ext_ratios),
#     trans = scales::trans_new(name = "ihs",
#                               transform = asinh,
#                               inverse = sinh)) +
#   ggplot2::scale_x_continuous(
#     breaks = create_plot_breaks(lower_lim = lower_ana_ratios,
#                                 upper_lim = upper_ana_ratios,
#                                 accuracy = 0.01,
#                                 round_func = floor),
#     labels = create_plot_labels(lower_lim = lower_ana_ratios,
#                                 upper_lim = upper_ana_ratios,
#                                 accuracy = 0.01,
#                                 round_func = floor),
#     limits = c(lower_ana_ratios, upper_ana_ratios),
#     trans = scales::trans_new(name = "ihs",
#                               transform = asinh,
#                               inverse = sinh))
#
# ggplot2::theme(title = ggplot2::element_text(size = 10),
#                text = ggplot2::element_text(size = 7),
#                axis.text.y = ggtext::element_markdown(),
#                axis.text.x = ggtext::element_markdown()) +
#   ggplot2::scale_y_continuous(
#     breaks = create_plot_breaks(lower_lim = lower_immig_ratios,
#                                 upper_lim = upper_immig_ratios,
#                                 accuracy = 0.001,
#                                 round_func = floor),
#     labels = create_plot_labels(lower_lim = lower_immig_ratios,
#                                 upper_lim = upper_immig_ratios,
#                                 accuracy = 0.001,
#                                 round_func = floor),
#     limits = c(lower_immig_ratios, upper_immig_ratios),
#     trans = scales::trans_new(name = "ihs",
#                               transform = asinh,
#                               inverse = sinh)) +
#   ggplot2::scale_x_continuous(
#     breaks = create_plot_breaks(lower_lim = lower_ana_ratios,
#                                 upper_lim = upper_ana_ratios,
#                                 accuracy = 0.01,
#                                 round_func = floor),
#     labels = create_plot_labels(lower_lim = lower_ana_ratios,
#                                 upper_lim = upper_ana_ratios,
#                                 accuracy = 0.01,
#                                 round_func = floor),
#     limits = c(lower_ana_ratios, upper_ana_ratios),
#     trans = scales::trans_new(name = "ihs",
#                               transform = asinh,
#                               inverse = sinh))
